name: Main Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
env:
  S3_BUCKET_NAME: unitysheepgameonline-origin
  AWS_REGION: us-east-1

jobs:
  build:
    name: Build WebGL
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-SheepGame-${{ hashFiles('**/ProjectSettings/ProjectSettings.asset') }}
          restore-keys: |
            Library-SheepGame-
            Library-
      - name: Extract branch name
        shell: bash
        run: |
          if [[ "${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" == "main" ]]; then
            echo "branch=" >> $GITHUB_OUTPUT
          else
            echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
          fi
        id: extract_branch
      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
      - uses: actions/upload-artifact@v3
        with:
          name: Build
          path: build
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::954266951730:role/github
          role-session-name: github
      - name: Sync files with S3
        run: aws s3 sync ./build/WebGL/WebGL/ s3://${{ env.S3_BUCKET_NAME }}/${{ steps.extract_branch.outputs.branch }}
